/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
import "sst"
declare module "sst" {
  export interface Resource {
    "api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "db": {
      "database": string
      "type": "sst.sst.Linkable"
    }
    "web": {
      "type": "sst.aws.SolidStart"
      "url": string
    }
  }
}
