/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as StaticLayoutImport } from './pages/_static/layout'
import { Route as ProtectedLayoutImport } from './pages/_protected/layout'
import { Route as ProtectedIndexImport } from './pages/_protected/index'
import { Route as StaticLandingImport } from './pages/_static/landing'
import { Route as StaticAboutImport } from './pages/_static/about'
import { Route as ProtectedAccountImport } from './pages/_protected/account'
import { Route as ProtectedGroupsLayoutImport } from './pages/_protected/groups/layout'
import { Route as ProtectedGroupsIndexImport } from './pages/_protected/groups/index'
import { Route as ProtectedGroupsTitleLayoutImport } from './pages/_protected/groups/$title.layout'
import { Route as ProtectedGroupsTitleIndexImport } from './pages/_protected/groups/$title.index'
import { Route as ProtectedGroupsTitleSettingsImport } from './pages/_protected/groups/$title.settings'
import { Route as ProtectedGroupsTitleMembersImport } from './pages/_protected/groups/$title.members'

// Create/Update Routes

const StaticLayoutRoute = StaticLayoutImport.update({
  id: '/_static',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedLayoutRoute = ProtectedLayoutImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedIndexRoute = ProtectedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const StaticLandingRoute = StaticLandingImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => StaticLayoutRoute,
} as any)

const StaticAboutRoute = StaticAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => StaticLayoutRoute,
} as any)

const ProtectedAccountRoute = ProtectedAccountImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedGroupsLayoutRoute = ProtectedGroupsLayoutImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedGroupsIndexRoute = ProtectedGroupsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedGroupsLayoutRoute,
} as any)

const ProtectedGroupsTitleLayoutRoute = ProtectedGroupsTitleLayoutImport.update(
  {
    id: '/$title',
    path: '/$title',
    getParentRoute: () => ProtectedGroupsLayoutRoute,
  } as any,
)

const ProtectedGroupsTitleIndexRoute = ProtectedGroupsTitleIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedGroupsTitleLayoutRoute,
} as any)

const ProtectedGroupsTitleSettingsRoute =
  ProtectedGroupsTitleSettingsImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedGroupsTitleLayoutRoute,
  } as any)

const ProtectedGroupsTitleMembersRoute =
  ProtectedGroupsTitleMembersImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProtectedGroupsTitleLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_static': {
      id: '/_static'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof StaticLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_protected/groups': {
      id: '/_protected/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof ProtectedGroupsLayoutImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/account': {
      id: '/_protected/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_static/about': {
      id: '/_static/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof StaticAboutImport
      parentRoute: typeof StaticLayoutImport
    }
    '/_static/landing': {
      id: '/_static/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof StaticLandingImport
      parentRoute: typeof StaticLayoutImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/groups/$title': {
      id: '/_protected/groups/$title'
      path: '/$title'
      fullPath: '/groups/$title'
      preLoaderRoute: typeof ProtectedGroupsTitleLayoutImport
      parentRoute: typeof ProtectedGroupsLayoutImport
    }
    '/_protected/groups/': {
      id: '/_protected/groups/'
      path: '/'
      fullPath: '/groups/'
      preLoaderRoute: typeof ProtectedGroupsIndexImport
      parentRoute: typeof ProtectedGroupsLayoutImport
    }
    '/_protected/groups/$title/members': {
      id: '/_protected/groups/$title/members'
      path: '/members'
      fullPath: '/groups/$title/members'
      preLoaderRoute: typeof ProtectedGroupsTitleMembersImport
      parentRoute: typeof ProtectedGroupsTitleLayoutImport
    }
    '/_protected/groups/$title/settings': {
      id: '/_protected/groups/$title/settings'
      path: '/settings'
      fullPath: '/groups/$title/settings'
      preLoaderRoute: typeof ProtectedGroupsTitleSettingsImport
      parentRoute: typeof ProtectedGroupsTitleLayoutImport
    }
    '/_protected/groups/$title/': {
      id: '/_protected/groups/$title/'
      path: '/'
      fullPath: '/groups/$title/'
      preLoaderRoute: typeof ProtectedGroupsTitleIndexImport
      parentRoute: typeof ProtectedGroupsTitleLayoutImport
    }
  }
}

// Create and export the route tree

interface ProtectedGroupsTitleLayoutRouteChildren {
  ProtectedGroupsTitleMembersRoute: typeof ProtectedGroupsTitleMembersRoute
  ProtectedGroupsTitleSettingsRoute: typeof ProtectedGroupsTitleSettingsRoute
  ProtectedGroupsTitleIndexRoute: typeof ProtectedGroupsTitleIndexRoute
}

const ProtectedGroupsTitleLayoutRouteChildren: ProtectedGroupsTitleLayoutRouteChildren =
  {
    ProtectedGroupsTitleMembersRoute: ProtectedGroupsTitleMembersRoute,
    ProtectedGroupsTitleSettingsRoute: ProtectedGroupsTitleSettingsRoute,
    ProtectedGroupsTitleIndexRoute: ProtectedGroupsTitleIndexRoute,
  }

const ProtectedGroupsTitleLayoutRouteWithChildren =
  ProtectedGroupsTitleLayoutRoute._addFileChildren(
    ProtectedGroupsTitleLayoutRouteChildren,
  )

interface ProtectedGroupsLayoutRouteChildren {
  ProtectedGroupsTitleLayoutRoute: typeof ProtectedGroupsTitleLayoutRouteWithChildren
  ProtectedGroupsIndexRoute: typeof ProtectedGroupsIndexRoute
}

const ProtectedGroupsLayoutRouteChildren: ProtectedGroupsLayoutRouteChildren = {
  ProtectedGroupsTitleLayoutRoute: ProtectedGroupsTitleLayoutRouteWithChildren,
  ProtectedGroupsIndexRoute: ProtectedGroupsIndexRoute,
}

const ProtectedGroupsLayoutRouteWithChildren =
  ProtectedGroupsLayoutRoute._addFileChildren(
    ProtectedGroupsLayoutRouteChildren,
  )

interface ProtectedLayoutRouteChildren {
  ProtectedGroupsLayoutRoute: typeof ProtectedGroupsLayoutRouteWithChildren
  ProtectedAccountRoute: typeof ProtectedAccountRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedGroupsLayoutRoute: ProtectedGroupsLayoutRouteWithChildren,
  ProtectedAccountRoute: ProtectedAccountRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

interface StaticLayoutRouteChildren {
  StaticAboutRoute: typeof StaticAboutRoute
  StaticLandingRoute: typeof StaticLandingRoute
}

const StaticLayoutRouteChildren: StaticLayoutRouteChildren = {
  StaticAboutRoute: StaticAboutRoute,
  StaticLandingRoute: StaticLandingRoute,
}

const StaticLayoutRouteWithChildren = StaticLayoutRoute._addFileChildren(
  StaticLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof StaticLayoutRouteWithChildren
  '/groups': typeof ProtectedGroupsLayoutRouteWithChildren
  '/account': typeof ProtectedAccountRoute
  '/about': typeof StaticAboutRoute
  '/landing': typeof StaticLandingRoute
  '/': typeof ProtectedIndexRoute
  '/groups/$title': typeof ProtectedGroupsTitleLayoutRouteWithChildren
  '/groups/': typeof ProtectedGroupsIndexRoute
  '/groups/$title/members': typeof ProtectedGroupsTitleMembersRoute
  '/groups/$title/settings': typeof ProtectedGroupsTitleSettingsRoute
  '/groups/$title/': typeof ProtectedGroupsTitleIndexRoute
}

export interface FileRoutesByTo {
  '': typeof StaticLayoutRouteWithChildren
  '/account': typeof ProtectedAccountRoute
  '/about': typeof StaticAboutRoute
  '/landing': typeof StaticLandingRoute
  '/': typeof ProtectedIndexRoute
  '/groups': typeof ProtectedGroupsIndexRoute
  '/groups/$title/members': typeof ProtectedGroupsTitleMembersRoute
  '/groups/$title/settings': typeof ProtectedGroupsTitleSettingsRoute
  '/groups/$title': typeof ProtectedGroupsTitleIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_protected': typeof ProtectedLayoutRouteWithChildren
  '/_static': typeof StaticLayoutRouteWithChildren
  '/_protected/groups': typeof ProtectedGroupsLayoutRouteWithChildren
  '/_protected/account': typeof ProtectedAccountRoute
  '/_static/about': typeof StaticAboutRoute
  '/_static/landing': typeof StaticLandingRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/groups/$title': typeof ProtectedGroupsTitleLayoutRouteWithChildren
  '/_protected/groups/': typeof ProtectedGroupsIndexRoute
  '/_protected/groups/$title/members': typeof ProtectedGroupsTitleMembersRoute
  '/_protected/groups/$title/settings': typeof ProtectedGroupsTitleSettingsRoute
  '/_protected/groups/$title/': typeof ProtectedGroupsTitleIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/groups'
    | '/account'
    | '/about'
    | '/landing'
    | '/'
    | '/groups/$title'
    | '/groups/'
    | '/groups/$title/members'
    | '/groups/$title/settings'
    | '/groups/$title/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/account'
    | '/about'
    | '/landing'
    | '/'
    | '/groups'
    | '/groups/$title/members'
    | '/groups/$title/settings'
    | '/groups/$title'
  id:
    | '__root__'
    | '/_protected'
    | '/_static'
    | '/_protected/groups'
    | '/_protected/account'
    | '/_static/about'
    | '/_static/landing'
    | '/_protected/'
    | '/_protected/groups/$title'
    | '/_protected/groups/'
    | '/_protected/groups/$title/members'
    | '/_protected/groups/$title/settings'
    | '/_protected/groups/$title/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
  StaticLayoutRoute: typeof StaticLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
  StaticLayoutRoute: StaticLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_protected",
        "/_static"
      ]
    },
    "/_protected": {
      "filePath": "_protected/layout.tsx",
      "children": [
        "/_protected/groups",
        "/_protected/account",
        "/_protected/"
      ]
    },
    "/_static": {
      "filePath": "_static/layout.tsx",
      "children": [
        "/_static/about",
        "/_static/landing"
      ]
    },
    "/_protected/groups": {
      "filePath": "_protected/groups/layout.tsx",
      "parent": "/_protected",
      "children": [
        "/_protected/groups/$title",
        "/_protected/groups/"
      ]
    },
    "/_protected/account": {
      "filePath": "_protected/account.tsx",
      "parent": "/_protected"
    },
    "/_static/about": {
      "filePath": "_static/about.tsx",
      "parent": "/_static"
    },
    "/_static/landing": {
      "filePath": "_static/landing.tsx",
      "parent": "/_static"
    },
    "/_protected/": {
      "filePath": "_protected/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/groups/$title": {
      "filePath": "_protected/groups/$title.layout.tsx",
      "parent": "/_protected/groups",
      "children": [
        "/_protected/groups/$title/members",
        "/_protected/groups/$title/settings",
        "/_protected/groups/$title/"
      ]
    },
    "/_protected/groups/": {
      "filePath": "_protected/groups/index.tsx",
      "parent": "/_protected/groups"
    },
    "/_protected/groups/$title/members": {
      "filePath": "_protected/groups/$title.members.tsx",
      "parent": "/_protected/groups/$title"
    },
    "/_protected/groups/$title/settings": {
      "filePath": "_protected/groups/$title.settings.tsx",
      "parent": "/_protected/groups/$title"
    },
    "/_protected/groups/$title/": {
      "filePath": "_protected/groups/$title.index.tsx",
      "parent": "/_protected/groups/$title"
    }
  }
}
ROUTE_MANIFEST_END */
