/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as StaticLayoutImport } from './pages/_static/layout'
import { Route as ProtectedLayoutImport } from './pages/_protected/layout'
import { Route as ProtectedPageImport } from './pages/_protected/page'
import { Route as ProtectedGroupsLayoutImport } from './pages/_protected/groups/layout'
import { Route as StaticLandingPageImport } from './pages/_static/landing.page'
import { Route as StaticAboutPageImport } from './pages/_static/about.page'
import { Route as ProtectedGroupsPageImport } from './pages/_protected/groups/page'
import { Route as ProtectedAccountPageImport } from './pages/_protected/account.page'
import { Route as ProtectedGroupsTitleLayoutImport } from './pages/_protected/groups/$title.layout'
import { Route as ProtectedGroupsTitlePageImport } from './pages/_protected/groups/$title.page'
import { Route as ProtectedGroupsTitleSettingsPageImport } from './pages/_protected/groups/$title.settings.page'
import { Route as ProtectedGroupsTitleMembersPageImport } from './pages/_protected/groups/$title.members.page'

// Create/Update Routes

const StaticLayoutRoute = StaticLayoutImport.update({
  id: '/_static',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedLayoutRoute = ProtectedLayoutImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedPageRoute = ProtectedPageImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedGroupsLayoutRoute = ProtectedGroupsLayoutImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const StaticLandingPageRoute = StaticLandingPageImport.update({
  id: '/landing/',
  path: '/landing/',
  getParentRoute: () => StaticLayoutRoute,
} as any)

const StaticAboutPageRoute = StaticAboutPageImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => StaticLayoutRoute,
} as any)

const ProtectedGroupsPageRoute = ProtectedGroupsPageImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedGroupsLayoutRoute,
} as any)

const ProtectedAccountPageRoute = ProtectedAccountPageImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedGroupsTitleLayoutRoute = ProtectedGroupsTitleLayoutImport.update(
  {
    id: '/$title',
    path: '/$title',
    getParentRoute: () => ProtectedGroupsLayoutRoute,
  } as any,
)

const ProtectedGroupsTitlePageRoute = ProtectedGroupsTitlePageImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedGroupsTitleLayoutRoute,
} as any)

const ProtectedGroupsTitleSettingsPageRoute =
  ProtectedGroupsTitleSettingsPageImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => ProtectedGroupsTitleLayoutRoute,
  } as any)

const ProtectedGroupsTitleMembersPageRoute =
  ProtectedGroupsTitleMembersPageImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => ProtectedGroupsTitleLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_static': {
      id: '/_static'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof StaticLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_protected/groups': {
      id: '/_protected/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof ProtectedGroupsLayoutImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedPageImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/groups/$title': {
      id: '/_protected/groups/$title'
      path: '/$title'
      fullPath: '/groups/$title'
      preLoaderRoute: typeof ProtectedGroupsTitleLayoutImport
      parentRoute: typeof ProtectedGroupsLayoutImport
    }
    '/_protected/account/': {
      id: '/_protected/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountPageImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/groups/': {
      id: '/_protected/groups/'
      path: '/'
      fullPath: '/groups/'
      preLoaderRoute: typeof ProtectedGroupsPageImport
      parentRoute: typeof ProtectedGroupsLayoutImport
    }
    '/_static/about/': {
      id: '/_static/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof StaticAboutPageImport
      parentRoute: typeof StaticLayoutImport
    }
    '/_static/landing/': {
      id: '/_static/landing/'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof StaticLandingPageImport
      parentRoute: typeof StaticLayoutImport
    }
    '/_protected/groups/$title/': {
      id: '/_protected/groups/$title/'
      path: '/'
      fullPath: '/groups/$title/'
      preLoaderRoute: typeof ProtectedGroupsTitlePageImport
      parentRoute: typeof ProtectedGroupsTitleLayoutImport
    }
    '/_protected/groups/$title/members/': {
      id: '/_protected/groups/$title/members/'
      path: '/members'
      fullPath: '/groups/$title/members'
      preLoaderRoute: typeof ProtectedGroupsTitleMembersPageImport
      parentRoute: typeof ProtectedGroupsTitleLayoutImport
    }
    '/_protected/groups/$title/settings/': {
      id: '/_protected/groups/$title/settings/'
      path: '/settings'
      fullPath: '/groups/$title/settings'
      preLoaderRoute: typeof ProtectedGroupsTitleSettingsPageImport
      parentRoute: typeof ProtectedGroupsTitleLayoutImport
    }
  }
}

// Create and export the route tree

interface ProtectedGroupsTitleLayoutRouteChildren {
  ProtectedGroupsTitlePageRoute: typeof ProtectedGroupsTitlePageRoute
  ProtectedGroupsTitleMembersPageRoute: typeof ProtectedGroupsTitleMembersPageRoute
  ProtectedGroupsTitleSettingsPageRoute: typeof ProtectedGroupsTitleSettingsPageRoute
}

const ProtectedGroupsTitleLayoutRouteChildren: ProtectedGroupsTitleLayoutRouteChildren =
  {
    ProtectedGroupsTitlePageRoute: ProtectedGroupsTitlePageRoute,
    ProtectedGroupsTitleMembersPageRoute: ProtectedGroupsTitleMembersPageRoute,
    ProtectedGroupsTitleSettingsPageRoute:
      ProtectedGroupsTitleSettingsPageRoute,
  }

const ProtectedGroupsTitleLayoutRouteWithChildren =
  ProtectedGroupsTitleLayoutRoute._addFileChildren(
    ProtectedGroupsTitleLayoutRouteChildren,
  )

interface ProtectedGroupsLayoutRouteChildren {
  ProtectedGroupsTitleLayoutRoute: typeof ProtectedGroupsTitleLayoutRouteWithChildren
  ProtectedGroupsPageRoute: typeof ProtectedGroupsPageRoute
}

const ProtectedGroupsLayoutRouteChildren: ProtectedGroupsLayoutRouteChildren = {
  ProtectedGroupsTitleLayoutRoute: ProtectedGroupsTitleLayoutRouteWithChildren,
  ProtectedGroupsPageRoute: ProtectedGroupsPageRoute,
}

const ProtectedGroupsLayoutRouteWithChildren =
  ProtectedGroupsLayoutRoute._addFileChildren(
    ProtectedGroupsLayoutRouteChildren,
  )

interface ProtectedLayoutRouteChildren {
  ProtectedGroupsLayoutRoute: typeof ProtectedGroupsLayoutRouteWithChildren
  ProtectedPageRoute: typeof ProtectedPageRoute
  ProtectedAccountPageRoute: typeof ProtectedAccountPageRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedGroupsLayoutRoute: ProtectedGroupsLayoutRouteWithChildren,
  ProtectedPageRoute: ProtectedPageRoute,
  ProtectedAccountPageRoute: ProtectedAccountPageRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

interface StaticLayoutRouteChildren {
  StaticAboutPageRoute: typeof StaticAboutPageRoute
  StaticLandingPageRoute: typeof StaticLandingPageRoute
}

const StaticLayoutRouteChildren: StaticLayoutRouteChildren = {
  StaticAboutPageRoute: StaticAboutPageRoute,
  StaticLandingPageRoute: StaticLandingPageRoute,
}

const StaticLayoutRouteWithChildren = StaticLayoutRoute._addFileChildren(
  StaticLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof StaticLayoutRouteWithChildren
  '/groups': typeof ProtectedGroupsLayoutRouteWithChildren
  '/': typeof ProtectedPageRoute
  '/groups/$title': typeof ProtectedGroupsTitleLayoutRouteWithChildren
  '/account': typeof ProtectedAccountPageRoute
  '/groups/': typeof ProtectedGroupsPageRoute
  '/about': typeof StaticAboutPageRoute
  '/landing': typeof StaticLandingPageRoute
  '/groups/$title/': typeof ProtectedGroupsTitlePageRoute
  '/groups/$title/members': typeof ProtectedGroupsTitleMembersPageRoute
  '/groups/$title/settings': typeof ProtectedGroupsTitleSettingsPageRoute
}

export interface FileRoutesByTo {
  '': typeof StaticLayoutRouteWithChildren
  '/': typeof ProtectedPageRoute
  '/account': typeof ProtectedAccountPageRoute
  '/groups': typeof ProtectedGroupsPageRoute
  '/about': typeof StaticAboutPageRoute
  '/landing': typeof StaticLandingPageRoute
  '/groups/$title': typeof ProtectedGroupsTitlePageRoute
  '/groups/$title/members': typeof ProtectedGroupsTitleMembersPageRoute
  '/groups/$title/settings': typeof ProtectedGroupsTitleSettingsPageRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_protected': typeof ProtectedLayoutRouteWithChildren
  '/_static': typeof StaticLayoutRouteWithChildren
  '/_protected/groups': typeof ProtectedGroupsLayoutRouteWithChildren
  '/_protected/': typeof ProtectedPageRoute
  '/_protected/groups/$title': typeof ProtectedGroupsTitleLayoutRouteWithChildren
  '/_protected/account/': typeof ProtectedAccountPageRoute
  '/_protected/groups/': typeof ProtectedGroupsPageRoute
  '/_static/about/': typeof StaticAboutPageRoute
  '/_static/landing/': typeof StaticLandingPageRoute
  '/_protected/groups/$title/': typeof ProtectedGroupsTitlePageRoute
  '/_protected/groups/$title/members/': typeof ProtectedGroupsTitleMembersPageRoute
  '/_protected/groups/$title/settings/': typeof ProtectedGroupsTitleSettingsPageRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/groups'
    | '/'
    | '/groups/$title'
    | '/account'
    | '/groups/'
    | '/about'
    | '/landing'
    | '/groups/$title/'
    | '/groups/$title/members'
    | '/groups/$title/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/'
    | '/account'
    | '/groups'
    | '/about'
    | '/landing'
    | '/groups/$title'
    | '/groups/$title/members'
    | '/groups/$title/settings'
  id:
    | '__root__'
    | '/_protected'
    | '/_static'
    | '/_protected/groups'
    | '/_protected/'
    | '/_protected/groups/$title'
    | '/_protected/account/'
    | '/_protected/groups/'
    | '/_static/about/'
    | '/_static/landing/'
    | '/_protected/groups/$title/'
    | '/_protected/groups/$title/members/'
    | '/_protected/groups/$title/settings/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
  StaticLayoutRoute: typeof StaticLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
  StaticLayoutRoute: StaticLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_protected",
        "/_static"
      ]
    },
    "/_protected": {
      "filePath": "_protected/layout.tsx",
      "children": [
        "/_protected/groups",
        "/_protected/",
        "/_protected/account/"
      ]
    },
    "/_static": {
      "filePath": "_static/layout.tsx",
      "children": [
        "/_static/about/",
        "/_static/landing/"
      ]
    },
    "/_protected/groups": {
      "filePath": "_protected/groups/layout.tsx",
      "parent": "/_protected",
      "children": [
        "/_protected/groups/$title",
        "/_protected/groups/"
      ]
    },
    "/_protected/": {
      "filePath": "_protected/page.tsx",
      "parent": "/_protected"
    },
    "/_protected/groups/$title": {
      "filePath": "_protected/groups/$title.layout.tsx",
      "parent": "/_protected/groups",
      "children": [
        "/_protected/groups/$title/",
        "/_protected/groups/$title/members/",
        "/_protected/groups/$title/settings/"
      ]
    },
    "/_protected/account/": {
      "filePath": "_protected/account.page.tsx",
      "parent": "/_protected"
    },
    "/_protected/groups/": {
      "filePath": "_protected/groups/page.tsx",
      "parent": "/_protected/groups"
    },
    "/_static/about/": {
      "filePath": "_static/about.page.tsx",
      "parent": "/_static"
    },
    "/_static/landing/": {
      "filePath": "_static/landing.page.tsx",
      "parent": "/_static"
    },
    "/_protected/groups/$title/": {
      "filePath": "_protected/groups/$title.page.tsx",
      "parent": "/_protected/groups/$title"
    },
    "/_protected/groups/$title/members/": {
      "filePath": "_protected/groups/$title.members.page.tsx",
      "parent": "/_protected/groups/$title"
    },
    "/_protected/groups/$title/settings/": {
      "filePath": "_protected/groups/$title.settings.page.tsx",
      "parent": "/_protected/groups/$title"
    }
  }
}
ROUTE_MANIFEST_END */
