import { createTable, uuidv7 } from './utils';

import { primaryKey } from 'drizzle-orm/pg-core';

/* 
    NOTE: this v is a good idea generated by ai

    lastUsedGroupId: uuidv7('last_used_group_id'),

    not going to implement now, but for the future we can use this, 
    probably w/ redis or something, to store the last used group id 
    for when a user is submitting often. this can time out and fall
    back to the default group id
*/

export const preferenceTable = createTable(
  'preference',
  {
    userId: uuidv7().notNull().unique(),
    defaultGroupId: uuidv7().notNull(),
  },
  (table) => [primaryKey({ columns: [table.userId, table.defaultGroupId] })],
);
